### ISSUE TITLE
Deploying to AWS elastic bean stalk

### ISSUE THREAD

**Issue by vinaygurram** [dbaggott/newrelic-dropwizard#8]
Hi, 
I use dropwizard framework and I deploy the application to AWS elasticbeanstalk. How can I deploy this plugin to elastic beanstalk?

I thought of adding installation instructions to .ebextensions. Is there any other way?

Thanks,
Vinay

**Comment by dbaggott** [comment]
I'm not very familiar with elasticbeanstalk so can't speak directly to it.  As of now, the general routes to installation are:
1. via New Relic's [NPI](https://docs.newrelic.com/docs/plugins/plugins-new-relic/installing-plugins/installing-npi-compatible-plugin) installer.
2. manually download the jar from github, manually create the configuration files, and directly run the plugin by invoking java

Generally, I recommend using NPI.  NR [documents](https://docs.newrelic.com/docs/plugins/plugins-new-relic/installing-plugins/installing-npi-compatible-plugin#download-npi) how to grab NPI via curl, and then you should be able to do the installation via a series of npi commands.

Note that the `npi install` command requires interaction so you'll probably need to take the ["manual" approach](https://docs.newrelic.com/docs/plugins/plugins-new-relic/installing-plugins/installing-npi-compatible-plugin#npi-commands) where you issue a series of commands...

I've used the 2nd approach when doing Chef-based installations and that might end up being easier.  But I'd try NPI first.

I'll look into creating a Docker container for this plugin (that would probably be the easiest for you) but I'm about to go on vacation for a couple weeks so I'm not likely to get to that very quickly.

In the meantime, please let me know how it goes...

It's also in my queue to add the ability to identify EC2-based Dropwizard instances by tags instead of by ip/hostname so that, for example, auto-scaled instances can be easily monitored without needing to maintain the plugin's configuration.  Out of curiosity, is that a problem for your use case or do you know up-front what all your EC2-based instances are going to be?

**Comment by vinaygurram** [comment]
Thanks for quick reply. 

May be you can help me better if I detail my issue. My ec2 instances for ElasticBeanstalk are in private subnet so there is no way to access dropwizard admin servlet from outside. So I had to install this plugin on every ec2 instance. And ElasticBeanstalk might change ec2 instances on deployment so I had to automate installation of the plugin.

Installation from NPI requires interaction and I am not familiar with chef/puppet and we have a release next week so I put the issue into low priority. 

I have installed new relic java agent with the app. If I can tweak the agent to include dropwizrd metrics and send the data to this plugin that would be awesome :). I am happy to contribute if you have an idea to how to get into the issue.

Thanks,
Vinay

**Comment by dbaggott** [comment]
> May be you can help me better if I detail my issue. My ec2 instances for ElasticBeanstalk are in private subnet so there is no way to access dropwizard admin servlet from outside. So I had to install this plugin on every ec2 instance. And ElasticBeanstalk might change ec2 instances on deployment so I had to automate installation of the plugin.

For this, the tag-based identification of EC2-based instances that I mentioned would (if it existed) be helpful.  Then you could have a dedicated node running the Dropwizard NR Plugin Agent running in the same private subnet and the agent could identify your DW instances dynamically at runtime based on EC2 instance tags..  As beanstalk changes EC2 instances, the agent would automatically keep up.  Unfortunately, that functionality doesn't exist.

However, you should be able to automate NPI installation using `npi config set license_key <your key>`, `npi fetch io.dnbg.newrelic.dropwizard`, etc as described under the [example flows](https://docs.newrelic.com/docs/plugins/plugins-new-relic/installing-plugins/installing-npi-compatible-plugin#npi-commands).  I think the only interactive step is `prepare` -- instead of running `npi prepare io.dnbg.newrelic.dropwizard`, you'll need to script the creation of the config files to the correct place. 

> I have installed new relic java agent with the app. If I can tweak the agent to include dropwizard metrics and send the data to this plugin that would be awesome :). I am happy to contribute if you have an idea to how to get into the issue.

In theory, that general approach should be possible by:
- including this library as a dependency within your DW application (it's not available in maven/gradle/etc so you'd need to package the jar up yourself)
- start a dedicated thread in your DW application that invokes code similar to [Main](/src/main/java/io/dnbg/newrelic/dropwizard/Main.java).
- make sure the required plugin/agent configuration files are available from within your DW app...

Then the agent will run from within DW, grab metrics/healthcheck data from localhost, and happily send it of to NR's server.

**Comment by dbaggott** [comment]
Feel free to comment further on this issue but closing in favor of #9, #10, and #11.

**Comment by vinaygurram** [comment]
> For this, the tag-based identification of EC2-based instances that I mentioned would (if it existed) be helpful. Then you could have a dedicated node running the Dropwizard NR Plugin Agent running in the same private subnet and the agent could identify your DW instances dynamically at runtime based on EC2 instance tags.. As beanstalk changes EC2 instances, the agent would automatically keep up. Unfortunately, that functionality doesn't exist.

That would be super awesome :-). This is depending on the fact that ebs is going to give ec2 same names as the application name. May be call aws api to list ec2 instances.

> However, you should be able to automate NPI installation using npi config set license_key <your key>, npi fetch io.dnbg.newrelic.dropwizard, etc as described under the example flows. I think the only interactive step is prepare -- instead of running npi prepare io.dnbg.newrelic.dropwizard, you'll need to script the creation of the config files to the correct place.  

NPI installation is easy to automate. But for me the problem is configuring plugin.json when installing the plugin. But still making all that into .ebexenstions seems complex to me.

> In theory, that general approach should be possible by:
> including this library as a dependency within your DW application (it's not available in maven/gradle/etc so you'd need to package the jar up yourself)
> start a dedicated thread in your DW application that invokes code similar to Main.
> make sure the required plugin/agent configuration files are available from within your DW app...
> Then the agent will run from within DW, grab metrics/healthcheck data from localhost, and happily send it of to NR's server.

This idea sounds good and fast to implement. I tested this out and it works too :-). If you can spare 10-15 minutes please take a look at [Sample](https://github.com/vinaygurram/NRDWPluginIntergrationSample).

**Comment by dbaggott** [comment]
Awesome -- I'll take a look at your sample when I get a chance.

Do note that there is a downside to this general approach: New Relic does not let you alert on the absence of data so if the reporting thread dies, your DW application crashes, the network becomes inaccessible, etc, etc you will not get an alert from the Dropwizard plugin.

But, as long as you have general monitoring around the server and the DW process itself, then the risks are mitigated...
